# Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"  # Use a suitable base box

  # AppFlowy
  config.vm.define "appflowy" do |appflowy|
    appflowy.vm.network "private_network", ip: "192.168.33.10"
    appflowy.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/appflowy_playbook.yml"
      # Other Ansible configurations for AppFlowy
    end
  end

  # Rocket.Chat.ReactNative
  config.vm.define "rocketchat_reactnative" do |rocketchat_reactnative|
    rocketchat_reactnative.vm.network "private_network", ip: "192.168.33.11"
    rocketchat_reactnative.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/rocketchat_reactnative_playbook.yml"
      # Other Ansible configurations for Rocket.Chat.ReactNative
    end
  end

  # Rocket.Chat
  config.vm.define "rocketchat" do |rocketchat|
    rocketchat.vm.network "private_network", ip: "192.168.33.12"
    rocketchat.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/rocketchat_playbook.yml"
      # Other Ansible configurations for Rocket.Chat
    end
  end
end
