Vagrant.configure("2") do |config|
  # Default base box
  config.vm.box = "ubuntu/focal64"

  # Define a function to configure each VM
  def configure_vm(config, name, ip, playbook)
    config.vm.define name do |vm|
      vm.vm.network "private_network", ip: ip
      vm.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/#{playbook}"
        # Add other Ansible configurations here
      end
    end
  end

  # List of VMs to provision
  vms = [
    { name: "appflowy", ip: "192.168.33.10", playbook: "appflowy_playbook.yml" },
    { name: "rocketchat_reactnative", ip: "192.168.33.11", playbook: "rocketchat_reactnative_playbook.yml" },
    { name: "rocketchat", ip: "192.168.33.12", playbook: "rocketchat_playbook.yml" }
  ]

  # Iterate over the VM list and configure each one
  vms.each do |vm_config|
    configure_vm(config, vm_config[:name], vm_config[:ip], vm_config[:playbook])
  end
end
